### ISSUE TITLE
Keyboard suddenly stopped working

### ISSUE THREAD

**Issue by lukeyxu** [pqrs-org/Karabiner-Elements#2247]
Noticed an issue, not sure if its regarding the Mac version updates. My keyboard will stop working, even laptop keyboard will stop work too. Only restart will solve this problem.

**Comment by fishcymbal** [comment]
I just noticed the same thing this morning. Trying to track it down. So many possibilities. Seems to be worse after invoking CAPS LOCK as meta key, regardless of secondary behavior.

**Comment by piotrszyma** [comment]
I have a similar issue and sometimes closing & reopening the lid helps.

**Comment by serverhiccups** [comment]
I’m currently having the same issue. For context, i use macOS 10.15.2 and Karabiner version 12.9.0. I have fn mapped to caps lock (for switching between Japanese keyboard layouts), so I press it fairly frequently. The keyboard doesn't stop working every time, which is a little odd. The only thing that I have found that fixes the issue is a restart.

If there's anything that I can do to help triage the source of this bug, then I'm willing to help.

**Comment by bbatsov** [comment]
I have the same problem myself. I've noticed a few related issues - https://github.com/pqrs-org/Karabiner-Elements/issues/2035 and https://github.com/pqrs-org/Karabiner-Elements/issues/2114 Guess I'll have to live without Karabiner for a while.

**Comment by chrisbellman** [comment]
+1. Closing the lid (and waiting for computer to go to sleep) and starting back up seems to help free up keyboard (but then remap is no longer active until restart). On Karabiner 12.9.0 & MacOS 10.15.4 (but it's been happening for a while). FYI I just have fn + option remapped (swapped). Would love to see this fixed.

**Comment by bbatsov** [comment]
> Closing the lid (and waiting for computer to go to sleep) and starting back up seems to help free up keyboard (but then remap is no longer active until restart).

I can confirm this worked for me as well. Funny enough - so far the bug happens only with the laptop keyboard, but it hasn't happened with my external keyboard.

**Comment by mwkcoding** [comment]
How is the devs not looking into this?

**Comment by m4rkw** [comment]
Happening for me as well. Catalina 10.15.5 (public beta) and latest karabiner release on a 2020 Macbook Air.

**Comment by m4rkw** [comment]
@tekezo I'll give you $50 USD to fix this, it's disrupting my work frequently and I sometimes have to reboot the machine to recover. I have to use Citrix for work so have no choice but to use Karabiner to make using windows tolerable. Happy to help with whatever debug logs or testing you need.

**Comment by trbielec** [comment]
@tekezo this is a **fatal** issue, please respond

Karabiner is 100% unusable on Catalina with these Caps Lock lockups and Full Buffers on the current version. Users cannot resolve with killall processes or reverting to previous releases. Many users have been mentioning these fatal errors for _months_.

**Comment by fishcymbal** [comment]
Somehow I got lucky and the problem went away on my mac and I'm only posting here to give some hope to the rest who are still dealing with it. 
Unfortunately, I'm not sure which did the trick exactly -- multiple reboots, an uninstall and reinstall of Karabiner, or removing and reinstalling the complex modifications files. 
For that last part, here's what I did specifically: I hit the "remove" button to take away my existing, customized script and then hit the "add item" button to get a fresh set of scripts. I chose a couple other caps lock options as alternatives, going back to one closest to my original. The problem disappeared. Maybe those of us having the issue were using old scripts that had elements that are now deprecated by the OS? I don't know, I'm not a developer.
It might be worth a try for everyone else who's been having the problem.

**Comment by m4rkw** [comment]
For me it's random throughout the day. Some days it works without issues, other days 1-3 times a day it will stop working. If I unplug and replug my external keyboard it often fixes it, but not always. I noticed that when it crashes if I press capslock on the internal keyboard (just to see if keyboard input is responding there) the light stays on and then it's screwed and I have to reboot.

**Comment by m4rkw** [comment]
We should probably also bear in mind that the next major release of macOS isn't going to allow kernel extensions at all so karabiner may not even be viable then.

**Comment by markwillis** [comment]
I used Caps Lock (which I don't often use) and had this same issue. 

After a load of messing around, I found this GH issue. A restart worked for me, but I agree that this a really bad workflow for me as I had to stop running a server in the middle of my work to solve this. Hopefully just an easy to fix edge case 🤷 🤞

**Comment by fflakito** [comment]
I have the same problem, I'm bringing one more cry to the pack ^^.

Setup: MacBook Pro 2013 with MacOS Catilina 10.15.5. Using a wireless PC (Logitech) keyboard.

Problem description: once in a while (everyday this I think...), both my keyboards (original laptop laptop + wireless keyboard) simply stop working.
I haven't stopped closing the lid, but simply unplugging the dongle and plugging it back allows me to type... but I don't have the remapping, and restarting Karabiner doesn't seem to help.

It is also a serious bug for me.

**Comment by grebulon** [comment]
Got this problem too on a new MacBook Pro 2020 with Catalina 10.15.5.
I also have the CapsLock mapped (to switch between languages) although I didn't notice this issue is related to it. I'll remove the mapping and try again.
Never had this before with the previous Mac. It's pretty bad because I've come to depend on K-E and I can't do without it.

**Comment by ajrt2118** [comment]
I'm going to +1 this as well. I have the Drevos Calibur and had no problem with Karabiner until I got a new Macbook and update to Catalina. I just updated to the latest release, 12.10.0, and it's still not recognizing my keyboard. This has been happening for a few weeks now. Is there a fix for this yet because all my mapped keys are gone and resetting them doesn't work. I'd rather not use the Window's keyboard shortcuts while working. :/

**Comment by HuirongWow** [comment]
I got the same problem , and restart is useless. On Catalina 10.15.5

**Comment by TediPapajorgji** [comment]
same problem for me on macbook pro 2018, catalina 10.15.4. Happens randomly when the caps lock key is pressed

**Comment by grebulon** [comment]
Could be a bug in Catalina
![Screen Shot 2020-07-19 at 15 51 58](https://user-images.githubusercontent.com/324996/87875215-6c945200-c9d8-11ea-99be-2bc237789158.png)

**Comment by narukami894** [comment]
hello, i updated to latest macOS (10.15.6) but still happened.

**Comment by heihachi316** [comment]
Hello,

I have the same trouble with Mac Pro Catalina version 10.15.6.
Switched FN with command.
Karabiner will fix it ?

**Comment by VladislavEkimtcov** [comment]
I would also like to add to the choir of voices experiencing this. 10.12.0 on a home computer  works fine. 10.15.5 the keyboard dying really messes with my job

**Comment by Anedumgottil** [comment]
Chiming in as well. Seeing the issue with Karabiner 10.12.0 and macOS 10.15.6

**Comment by grebulon** [comment]
Catalina 10.15.6 is better than the previous version, but there are still issues with USB devices, and a reboot is still needed several times a week.

**Comment by techsafe123** [comment]
experiencing the same problem. nothing to add.

**Comment by VladislavEkimtcov** [comment]
Okay, it managed to break in a new way today. Karabiner simply stopped interpreting key rebindings. I'll try to reboot to see of that helps.

**Comment by umurcg** [comment]
I have same problem with karabiner. It is a major bug occurs in mac os x catalina, and makes the software useless.

**Comment by EvansMatthew97** [comment]
I occasionally get this problem when pressing caps lock. Restarting is the only thing that fixes the issue. Touchbar and trackpad keep working fine, but the keyboard gets stuck with caps lock on (you can see the LED) and none of the keys work.

**Comment by Akhilkokani** [comment]
Even I am facing the same issue, to add context I am using MBP 2012 with MacOS Sierra 10.12.6, randomly left-shift key is not detected by K-E.

Restarting MBP solves it temporarily.

Note I have mapped all my not-working keys to eject button.

**Comment by kemalsanli** [comment]
I am also facing same issue on my hack.

**Comment by grebulon** [comment]
Guys, this doesn't seem to be a Karabiner bug - I suspect it's because of Apple's buggy USB driver. It was buggy since version 10.13 (or before) and it seems to go downhill.
No point in reporting more of the same, at least until the next version.

**Comment by VladislavEkimtcov** [comment]
> Guys, this doesn't seem to be a Karabiner bug - I suspect it's because of Apple's buggy USB driver. It was buggy since version 10.13 (or before) and it seems to go downhill.
> No point in reporting more of the same, at least until the next version.

Can this be fixed by transferring the driver from the previous build of macOS? ie that works for getting the "charge left" time back

**Comment by atanasj** [comment]
I am experiencing a similar issues... Left shift, control, and option key do not work. Got it to work by disabling caps lock and restarting. Worked for about 10 hours, then stopped again. Restart does not fix and this even interferes with an SRC reset as these keys are disabled. So now I'm stuck with no left shift, control, option. I've run built in diagnostics and no hardware issues are coming up (apart from the NVME drive I installed on this machine-Macbook Pro 13", late-2013).

Any ideas?? I've tried many of the proposed solutions across this repo and non work. 

macos 10.15.6 and KE 12.10.0.

**Comment by stephenheron** [comment]
Ah thank goodness this is a known issue, it's been driving me crazy. 

Are there any logs that we can pull that would be useful in debugging this issue?

**Comment by trungbui2000** [comment]
I can confirm that karabiner has been super buggy for me as well

**Comment by kanazaca** [comment]
Is there an estimation for this issue? It's really annoying the keyboard disconnecting randomly and i have to restart to make it work again.

**Comment by VladislavEkimtcov** [comment]
So far the solution that I found is to never ever use the CAPS LOCK key :)

**Comment by chrisbellman** [comment]
Does anyone know if this was fixed in v13 that was released yesterday? Hope so (and then we can close this issue)

**Comment by mredig** [comment]
Karabiner randomly stops working for me as well. Today I noticed it was EXACTLY when I hit caps lock, which correlates with earlier posts. the behavior was that the entire keyboard was non responsive until I force quit all karabiner executables at which point the keyboard worked again, just without the remapping.

Rebooting resolves the issue.

**Comment by tkambler** [comment]
I *might* have a fix for this (so far - so good). Try going into Karabiner Elements preferences. Click the _Devices_ tab, and if there are any random entries for things like _USB Receiver (Logitech)_, etc..., make sure they are un-checked. Post Catalina update, that was checked for me. I unchecked it, and so far the caps lock hanging issue has not repeated for me.

**Comment by chrisbellman** [comment]
v13 seems to have partially fixed this issue, FYI. It still does happen sporadically, but the main difference is that if you QUIT Karabiner-Elements, the computer goes back to normal (no restart required!). So I think the underlying bug is still there but the switch to DriverKit made it recoverable without a restart, which certainly makes this bug less critical.

**Comment by chrisbellman** [comment]
13.1.0 claims to have fixed this! https://karabiner-elements.pqrs.org/docs/releasenotes/#karabiner-elements-1310

**Comment by Carsair** [comment]
But v13 is broken too https://github.com/pqrs-org/Karabiner-Elements/issues/2456
And the solution there is to downgrade....

**Comment by howardsuuu** [comment]
Same issue here with Catalina 10.15.7, I set my F6 - F11 keys as media control but now they aren't working. Tried reboot OS and reinstalled Karabiner. It worked just fine seconds ago.

**Comment by GorvGoyl** [comment]
capslock key is still disabling the keyboard. 
macOS: Monterey 12.2.1

**Comment by mosheavni** [comment]
> capslock key is still disabling the keyboard. macOS: Monterey 12.2.1

for me as well, for the last couple of days. 2 different macbook pro's are randomly loosing connection to the USB keyboard.

**Comment by paragbaxi** [comment]
same here, have to unplug and plug in usb keyboard, then it works

**Comment by axeltidemann** [comment]
Same issue on Monterey 12.6, Karabiner-elements 14.10.0. I noticed that the globe key sometimes resets in System Preferences, but resetting it to "Do Nothing" does not solve the issue.

**Comment by iamtodor** [comment]
Perhaps the related issue here: from time to time my binds just vanish. So I need to restart the laptop and it's fine. I believe if I would have this logic https://github.com/pqrs-org/Karabiner-Elements/issues/3248 I could trace changes. I mean if the config file is under the git, it was committed and then the bindings stop working perhaps the configuration has been changed. But currently, it's not possible

**Comment by khilangudka** [comment]
Am also seeing this issue on MacOS Ventura 13.0 with Karabiner-Elements 14.10.0. Keyboard stops responding after I resume my MacBook Pro from sleep. Restarting Karabiner-Elements seems to fix it.

**Comment by j-martin** [comment]
I also have the same issue as @khilangudka on a 2017 15in MBP (Intel). My M1 Pro, and M1 Macbook Air seem to be unaffected. They are all running macOS 13.0.0 / 13.0.1.

This is an issue if macOS decides to require me to type the password instead of allowing TouchID. At this point, I have to restart the machine.

**Comment by khilangudka** [comment]
Funnily enough, I'm also on a 2017 15in MBP (Intel).

**Comment by laktak** [comment]
I'm usually on the lock screen when this happens. 

Is it possible to automatically disable Karabiner when the MBP gets locked?

**Comment by wados77** [comment]
It happens for me as well on my mac-mini M2 2023 with USB keyboard on macOS 14.3.1 (Sanoma), it's not depend on the Karabiner software (cause I'm not using it :), I presume the issue either with IOUSB stack or with some sleep events.

I've found 2 workarounds which allow me do not reboot/restart mac:

1. If it happened when mac is on lock screen you need to have 2 user accounts and using mouse/trackpad push button to switch users
2. If it happened during unlocked and working mac you need using mouse/trackpad go to:
System Settings -> Keyboard -> Text Input -> Input Sources -> Edit -> Use the Caps Lock key to switch to and from U.S. -> turn on/off
In both of these cases keyboard start works again!
I didn't check these workarounds on mac with internal keyboard

**Comment by mpr1255** [comment]
This is still happening to me (M3, Karabinder version 15.2.0). Bindings randomly stop. Doing the trick mentioned by nejmeijer (turning caps on and off for changing languages) "fixes" it. Very unfortunate. Will have to find a replacement I think.

**Comment by ylluminarious** [comment]
> It happens for me as well on my mac-mini M2 2023 with USB keyboard on macOS 14.3.1 (Sanoma), it's not depend on the Karabiner software (cause I'm not using it :), I presume the issue either with IOUSB stack or with some sleep events.
> 
> I've found 2 workarounds which allow me do not plug/unplug keyboard and restart mac:
> 
>     1. If it happened when mac is on lock screen you need to have 2 user accounts and using mouse/trackpad push button to switch users
> 
>     2. If it happened during unlocked and working mac you need using mouse/trackpad go to:
>        System Settings -> Keyboard -> Text Input -> Input Sources -> Edit -> Use the Caps Lock key to switch to and from U.S. -> turn on/off
>        In both of these cases keyboard start works again!
>        I didn't check these workarounds on mac with internal keyboard

@wados77 Thank you! Your suggestion seems to help with this issue as well: https://github.com/pqrs-org/Karabiner-Elements/issues/3044
