### ISSUE TITLE
Karabiner-NotificationWindow occupying 90+% CPU after waking up from sleep

### ISSUE THREAD

**Issue by hieast** [pqrs-org/Karabiner-Elements#2780]
Every time my macbook waked up from a "long" sleep, it became sluggish. A long sleep maybe an hour or more?

I check the Activity Monitor and sampled the process when it occupying 90+% CPU, and hope someone can solve this problem or tell me what else I can do to solve this problem. 

Many thanks for help!

[Sample of Karabiner-NotificationWindow when it takes 90+% CPU](https://gist.github.com/hieast/462640cc42f3c5d0cdb773862130edff)

macOS version: macOS 11.4 (20F71)
Karabiner version: Karabiner-Elements 13.5.0
Your Mac hardware: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
Your keyboard hardware: FILCO Bluetooth

Related issues #1958

**Comment by kennir** [comment]
I have the same issue, the system is very slow and no response after waked up

macOS 11.5
Karabiner: 13.5.0
MacBook Pro 16-inch 2019


Thanks

**Comment by phaseOne** [comment]
Same issue, similar hardware. Seems to cause a high load on WindowServer as well. I can work around the issue by terminating the Karabiner-NotificationWindow process, but it takes a few minutes to get to Activity Monitor as the system is so sluggish.

macOS version: macOS 11.5
Karabiner version: Karabiner-Elements 13.5.0
Your Mac hardware: MacBook Pro (15-inch, 2019)
Your keyboard hardware: Razer BlackWidow Ultimate, Logitech USB Receiver / Unifying Device
Your other hardware: CalDigit TS3 Thunderbolt Hub + 2 LG 27UD68 monitors, All USB devices routed through the hub.

**Comment by rdsharma** [comment]
I am also experiencing this. It happens even when my laptop has no devices plugged into it.

**Comment by rnsc** [comment]
Same issue for me on an M1 MacBook Pro.
1 external keyboard and 1 external mouse on Bluetooth.
Is there a way to run Karabiner Elements in debug mode to assess this issue?

**Comment by notnotjake** [comment]
Having similar issues on M1 Max MacBook Pro. Happening every other day: I hear fans, check iStatMenus and see `Karabiner-NotificationWindow` taking lots of CPU along with WindowServer for about 20 mins before I notice. Restarting Karabiner seems to fix but while restarting, the Mac is completely unresponsive or worse. Today it kicked me to login screen. There are crash reports and spin reports for WindowServer in Console, but nothing for karabiner. 
Looking at Karabiner logs, it _seems_ to be occurring when a USB keyboard is disconnected, but not every time.

**Comment by flashing** [comment]
Yesterday this issue occurred again on Macbook pro 2017 with big sur system, Karabiner 13.5. So I was looking for a newer version and upgraded Karabiner to 14.2, it works until now.
Actually it spend me a lot time to realize and find out what is going wrong when system is stuck(Karabiner-NotificationWindow CPU usage problem), especially when I was using Karabiner version 12.x, I use Logi mx master 3 mouse and set thumb wheel button to adjust system volume inside Logi options software , this bug always comes out.
Has this bug been fixed in version 14.2?

**Comment by sebastiankade** [comment]
+1

**Comment by notnotjake** [comment]
@flashing I've upgraded to 14.2.0 and still have the same issue.
I'm on an M1Max running Monterey. I do also have a Logi MX Master Mouse 3, but don't have the Logi software installed.

**Comment by flashing** [comment]
> @flashing I've upgraded to 14.2.0 and still have the same issue. I'm on an M1Max running Monterey. I do also have a Logi MX Master Mouse 3, but don't have the Logi software installed.

Yes this happen again just now, I have no idea whether this is relevant to better touch tool? Because I have set some shortcut keys in BTT, which is based on Karabiner's key mapping function? But still, stuck occurred when I adjust volume with MX master 3 mouse.

**Comment by notnotjake** [comment]
14.2.0 does make restarting KE much faster and less disruptive on my system, so when the problem happens, it's quicker to take care of it. And I don't have better touch tools, so I don't think that's necessarily part of the problem

**Comment by notnotjake** [comment]
After updating to 14.2.0, the issue is much more frequent, happening multiple times per day now.

**Comment by Write** [comment]
Same here on M1 Max 14", Trying the 14.2.2 beta to see how it goes

**Comment by arkadiusz-konopka-collibra** [comment]
+1

**Comment by notnotjake** [comment]
Any improvements on 14.2.2 ? Also is anyone having this issue and _not_ on an M1 Mac?

**Comment by Write** [comment]
14.2.2 Made the issue appear once, and never again since from what I recall.
But at the same time I do some testing (for other reasons) with Amphetamine so my results might not be accurate

**Comment by Write** [comment]
I turned  on Amptheatmine with "Allow display to sleep while lid closed" and "Allow display sleep" and got the issue again, it's literally unusuable since it's so laggy it's hard to go kill the process

**Comment by sebastiankade** [comment]
Definitely something to do when there are no devices connected, happens a lot more... brings my new macbook pro to it's knees 😭

**Comment by filippoferrari** [comment]
I'm on a M1 Pro 14", I've just updated to 14.3.0 and it is now happening more frequently than 14.2.0.

**Comment by Write** [comment]
Weirdly, I got the bug only twice since 14.2.2, Running in clamshell mode all the time, no idea what cause this.

**Comment by ohlin** [comment]
Experiencing the same issue here.

After Karabiner has been running for a while, changing the volume or brightness using an external keyboard (Planck running QMK) causes the `Karabiner-NotificationWindow` process to spike super high CPU usage for a short time, with the amount of time spent at high CPU usage increasing with subsequent taps of the volume or brightness keys. 

Restarting Karabiner fixes the issue at least for a while, but the restart process locks up the system entirely for about a minute.

System details:
- Karabiner 14.3.0
- MacOS 12.0.2 (Monterey)
- M1 Pro
- Planck keyboard running QMK
- Logitech MX Master 3 mouse w/ logi options running
- Not running BTT

**Comment by notnotjake** [comment]
I have a mechanical keyboard with QMK, MX Master Mouse (not using Logi Options), but I can't reliably trigger the issue. For me it seems to be associated with connecting or disconnecting my mechanical keyboard and waking the computer.
Also for me, in 14.3.0 restarting is very fast after I uninstalled and reinstalled, you may want to try that to avoid the minute of it being unresponsive.

**Comment by notnotjake** [comment]
I don't know much about this project, but is there any other way to report an issue directly or get an issue higher priority. I don't think anyone who actually works on the project is aware of this issue.

**Comment by issmirnov** [comment]
Per comment above, tagging @tekezo directly as he's the most active contributor to the repo. This issue is impacting a large number of folks on M1 + Monterey making Karabiner Elements unusable.

Thank you!

**Comment by Write** [comment]
Now I think about it, i had a QMK Keyboard too before switching too Apple's native wireless one (With touch ID), and iirc I didn't encountered the bug since then.

**Comment by michielappelman** [comment]
It has not happened often anymore, but it has happened with my 'regular' Apple Magic keyboard (without Touch ID) at least once with v14.3.0. I sometimes use the keyboard over Bluetooth, but mostly with the Lightning-USB-C cable connected through a USB-C hub (Hyperdrive Thunderbolt 3 USB-C Hub connected to MacBook Pro (16-inch, 2019) with Monterey 12.0.1).

Unfortunately, I have not kept a log if the issue happens when it's wired vs. wirelessly connected, but my feeling is that it's related to the wired USB connection, because I remember it happening most often when (dis)connecting that USB-C hub.

**Comment by ericboehs** [comment]
I too have a QMK keyboard, a Logitech mouse, and an Apple wireless with Touch ID and I had this problem.

I went to the Devices preference tab in Karabiner and unchecked all the devices except my internal keyboard (M1 MacBook Pro) and my Apple wireless. (I also rebooted.)

This works fine for me as I don't use Karabiner customizations on my mouse or QMK keyboard.

So far so good! I'm sure I'll report back if I start having problems again.

**Comment by DominikPeters** [comment]
I don't know what NotificationWindow is good for anyways, I've never seen such a window, and the code for the app doesn't look particularly useful for anything?

I've deleted the app on my system.

```
killall Karabiner-NotificationWindow
sudo rm -rf /Library/Application\ Support/org.pqrs/Karabiner-Elements/Karabiner-NotificationWindow.app
sudo rm -f '/Library/LaunchAgents/org.pqrs.karabiner.NotificationWindow.plist'
```

**Comment by notnotjake** [comment]
Well that's one way to solve the issue. I saw a notification window once, but it's been a few years
Interested to hear how it goes and if there are any side effects

**Comment by phaseOne** [comment]
I've done a similar, yet non-destructive, mitigation with no ill-effects. The following stops Karabiner-NotificationWindow:

```
sudo launchctl bootout gui/${UID}/org.pqrs.karabiner.NotificationWindow
```

You'll need to run that each time you launch Karabiner, as the app itself [manages the state of the LaunchAgent](https://github.com/pqrs-org/Karabiner-Elements/blob/fdc9d542a6f17258655f595e4d51d1e26aa25d41/src/share/launchctl_utility.hpp#L94). Hence, calling `launchctl unload` is insufficient.

I've dug into this issue a bit, but I don't have the time to debug it further at the moment. Karabiner-NotificationWindow is a small app. It subscribes to [`NSApplication.didChangeScreenParametersNotification`](https://developer.apple.com/documentation/appkit/nsapplicationdidchangescreenparametersnotification?language=objc) events and creates some transparent windows that are used to present notifications. It also runs some `updateWindowsVisibility()` window reordering method at the end of that event callback. There's also a callback from [karabiner_notification_message.json / notification_message_manager](https://github.com/pqrs-org/Karabiner-Elements/blob/bc71379fa0766e461659518ca91f37dc0b8fd9d1/src/share/notification_message_manager.hpp) that runs the same visibility method, but it also attempts to parse the JSON file and update a `NotificationMessage` singleton's `text` property. I haven't examined that manager or singleton too much. I see that notification_message_manager is referenced in [post_event_to_virtual_devices.hpp](https://github.com/pqrs-org/Karabiner-Elements/blob/22c72691a0ee9ce7ddca02e42cef121a00281a7e/src/share/manipulator/manipulators/post_event_to_virtual_devices/post_event_to_virtual_devices.hpp) and [device_grabber.hpp](https://github.com/pqrs-org/Karabiner-Elements/blob/fdc9d542a6f17258655f595e4d51d1e26aa25d41/src/core/grabber/include/grabber/device_grabber.hpp).

I suspect the issue is caused either by a flood of events that forces the window reordering code to run too frequently, or an issue with the JSON parsing, or some thread deadlocking issue. 🤷

**Comment by Mr-Sheep** [comment]
> I've done a similar, yet non-destructive, mitigation with no ill-effects. The following stops Karabiner-NotificationWindow:
> 
> ```
> sudo launchctl bootout gui/${UID}/org.pqrs.karabiner.NotificationWindow
> ```
> 
> You'll need to run that each time you launch Karabiner, as the app itself [manages the state of the LaunchAgent](https://github.com/pqrs-org/Karabiner-Elements/blob/fdc9d542a6f17258655f595e4d51d1e26aa25d41/src/share/launchctl_utility.hpp#L94). Hence, calling `launchctl unload` is insufficient.

I used [santa](https://github.com/google/santa) to blacklist the `Karabiner-NotificationWindow.app` process, so far no problem **yet**
```
sudo santactl rule --silent-block --path /Library/Application\ Support/org.pqrs/Karabiner-Elements/Karabiner-NotificationWindow.app/
```
note that after adding Karabiner-NotificationWindow.app to the blacklist you'll have to kill the Karabiner-NotificationWindow.app process manually once, and the screen will freeze for seconds before logging you out.

**Comment by linroex** [comment]
I has same problem

macOS: 12.1
M1 Pro 8 core macbook pro 2021
karabiner 14.3.0

**Comment by notDavid** [comment]
Same problem here, problem occurs multiple times daily:

Karabiner 14.3.0
macOS 12.1 Monterey
M1 Pro Max

I don't use an external mouse / keyboard.

**Comment by kennir** [comment]
It's a bit strange, a previous version seems to have fixed this problem, but this latest version (14.3.0) appears again

**Comment by porsager** [comment]
Also experiencing this issue with 14.3.0

**Comment by notnotjake** [comment]
Are there any alternatives to KE? It's gotten much worse for me. Now every time I restart KE, it logs me out and happening daily.

**Comment by Write** [comment]
> Are there any alternatives to KE? It's gotten much worse for me. Now every time I restart KE, it logs me out and happening daily.

WEll, there's a workaround few messages above

**Comment by tekezo** [comment]
I cannot reproduce the issue and cannot determine the cause from the sample.
Could you show me the following information?

- File contents of `/Library/Application Support/org.pqrs/tmp/karabiner_notification_message.json`
- Log messages when this issue happened https://karabiner-elements.pqrs.org/docs/manual/operation/log/

**Comment by kennir** [comment]
It looks empty

```bash
❯ cat karabiner_notification_message.json
{
    "body": ""
}%
```

**Comment by notnotjake** [comment]
Yep. Same here.

**Comment by Write** [comment]
The only thing I can say is that I never ever encountered the bug again when using my Apple Wireless Keyboard (with touch ID, if that matter).

**Comment by notnotjake** [comment]
Just happened, here are my logs: https://drive.google.com/drive/folders/1A8NvrKIOj7t1xKBdQaTK6-LKuNYGg8kr?usp=sharing

**Comment by tekezo** [comment]
Thank you for the information.
Especially, notnotjake's log shows that the device is repeatedly initialized and terminated in grabber process, which makes sense as a cause of the increased CPU usage.
I continue investigation.

**Comment by tekezo** [comment]
@notnotjake 
As for the behavior of the grabber process, the hardware (MX Master Mouse) itself seemed to be repeatedly connecting and disconnecting.
I didn't find any software problems yet, unfortunately.

By the way, if you disable the MX Master Mouse from devices, does the issue stop?
https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-devices/

**Comment by notnotjake** [comment]
Thank you very much for taking the time to look into this issue! I really appreciate it 🙏
I disabled the MX Master Mouse in KE, but after a few hours, I experienced the issue. However, this time it only lasted a 10-15 seconds and there was no activity in any of the logs for the time when the spike occurred.

**Comment by notnotjake** [comment]
I was experimenting with the complex modification `set_notification_message` to see if there was anything weird with that in relation to the issue. 
When I had an instance of the issue this morning, I triggered the notification with the right shift key. As soon as the notification window popped up, Karabiner-NotificationWindow dropped back down to normal CPU usage. 
I don't know if this is helpful, but it seemed somewhat interesting.

**Comment by neleid** [comment]
I have same problem and restarting KE sometimes cause MacOS down to restart.
My environment:
- MacBook Pro (M1 Max)
- MX Master 3 mouse
- Magic Keyboard with Numeric Keypad (Apple)
- 2 External Display (just in case. but, KE seems to spike high CPU usage when WindowServer process goes high CPU usage. )

**Comment by tkhg** [comment]
have the same issue every morning when I wake my m1pro 14" from sleep
need to close karabiner-elements and everything resumes after that

- Karabiner-Elements version: 14.3.0
- MacBook M1 Pro 14"

**Comment by moffatman** [comment]
It's really easy to reproduce by changing screen resolution, the Notification window will take 100% CPU for about 10-15 seconds. I built a new copy from source in an attempt to determine the root cause, but with my new version instead (no modifications), CPU usage only spikes to 10% for ~1 second upon changing screen resolution. So the problem may have been resolved in a recent commit and fix might be included in the next release.

**Comment by stephancasas** [comment]
+1 for the same issue on 14-inch M1 MBP. I run into the issue on wake from sleep and when disconnecting from Sidecar setup as an extended display.

**Comment by ohperhaps** [comment]
Same problem in my mac.
MBP 15-inch Monterey 12.1
Karabiner 14.3.0

**Comment by niklaas** [comment]
> It's really easy to reproduce by changing screen resolution, the Notification window will take 100% CPU for about 10-15 seconds. I built a new copy from source in an attempt to determine the root cause, but with my new version instead (no modifications), CPU usage only spikes to 10% for ~1 second upon changing screen resolution. So the problem may have been resolved in a recent commit and fix might be included in the next release.

If this really is fixed in a new commit, when is the next release to be expected? The issue is super annoying. I am already thinking about getting a (paid) alternative. I am also happy to pay a bounty for this to get fixed quickly.

<img width="951" alt="CleanShot 2022-02-08 at 10 37 51@2x" src="https://user-images.githubusercontent.com/705637/152960804-74d80062-1f13-44d2-bc98-8e8f80cd800c.png">

**Comment by niklaas** [comment]
> @niklaas , see @phaseOne's solution to kill the process:
> 
> > `sudo launchctl bootout gui/${UID}/org.pqrs.karabiner.NotificationWindow`
> 
> If you actually use the set_notification_window in your complex mods, this is not a solution, but for me it has completely solved my issue. You can also use Santa ([@Mr-Sheep's solution](https://github.com/pqrs-org/Karabiner-Elements/issues/2780#issuecomment-997173581)) to block it from ever running, or delete the notification window app ([@DominikPeters Solution](https://github.com/pqrs-org/Karabiner-Elements/issues/2780#issuecomment-991400159))

@notnotjake thanks a lot for summarizing the solutions! 🙇🏼 Really appreciated! Will try them. 😌

**Comment by AprilArcus** [comment]
Also experiencing this on a 16" M1, macOS 12.2.1 and Karabiner Elements 14.3.0. Happy to help if I can.

**Comment by tekezo** [comment]
I added a workaround for this issue at v14.3.1.
Could you confirm whether the latest beta version fixes this issue?

How to upgrade to the latest beta version:
![Check for beta updates](https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/images/karabiner-elements-check-for-updates-beta@2x.png)

**Comment by notnotjake** [comment]
So far, this seems to have fixed this issue.

**Comment by Krillko** [comment]
Using the beta since sunday morning, and the problem seems fixed.

**Comment by tekezo** [comment]
Thank you for confirmation!
I released Karabiner-Elements 14.4.0 with this fix.

**Comment by Neo-peng** [comment]
> Thank you for confirmation! I released Karabiner-Elements 14.4.0 with this fix.

Unfortunately, I observed same problem today. This is the first time, not sure if this will happen again.

System details:
- Mac mini m1
- karabiner-elements version 14.4.0
- logitech G102 mouse
- Niz 68EC-S keyboard

**Comment by seheonCho** [comment]
I had the same symptoms in version 14.3.0, but I checked the issue and finished the update.

I always use it well. Thank you.
