### ISSUE TITLE
Function keys as function keys no longer works in 15.1.0

### ISSUE THREAD

**Issue by wosc** [pqrs-org/Karabiner-Elements#3954]
Thanks for making Karabiner, it's an essential part of me being able to use macOS efficiently. :) After updating to the current version, neither explicitly mapping each function key to "itself", nor the nice toggle "use as standard function keys" has any effect anymore, pressing e.g. f10 always triggers the "volume mute" function now. Please let me know if there's anything I can do to help debug this. Thanks for your help!

![Screenshot 2024-10-07 at 10 42 02](https://github.com/user-attachments/assets/7224cc66-3fd7-49b0-b11f-9ace07698fc9)

**Comment by tekezo** [comment]
Thank you for feedback!
Due to macOS's internal processing, it was found that with the new virtual keyboard introduced in version 15.1.0, this setting needs to be changed through System Settings. 

In v15.2.0, I have made adjustments to open System Settings instead of change the setting directly, so please try opening the System Settings from here and adjust the settings.

version 15.2.0:
https://karabiner-elements.pqrs.org/docs/releasenotes/

<img width="1100" alt="Screenshot 2024-10-08 at 0 18 30" src="https://github.com/user-attachments/assets/73fc7912-239a-4b27-a337-6e3b47da27f7">

**Comment by tiojoca** [comment]
Any rules outputting a function key are now outputting whatever is set for that function key if that setting is not on. For example, this should send F2 when Caps Lock is pressed but is sending `display_brightness_increment` instead (the default in my keyboard for that key):
<img width="576" alt="image" src="https://github.com/user-attachments/assets/83aa283f-6de5-4b98-8cb7-c6e0d5ab46d2">

Also does this change mean this screen is now completely useless? If the function keys are set to work as standard function keys in System Settings, the settings in this page won't do anything.

**Comment by tekezo** [comment]
@tiojoca Please try turning the “Use all F1, F2, etc. keys as standard function keys” setting off and then on again from the System Settings. This will allow your caps lock to be processed as f2.

**Comment by tiojoca** [comment]
Thank you for your swift reply.

Yes that's true but if I have that setting on I can't use the function keys as "media keys". The settings in Karabiner's Function keys settings page are just ignored. I'd like to have the function keys outputting other values when the Fn key is not pressed but still be able to have another key or key combination output a function key (ie, `"to": [{ "key_code": "f2" }]` should output F2 regardless of what's currently attributed to the physical key F2).

**Comment by bdarfler** [comment]
Coming here to say the same. I have used a mix of media controls for f1-6 and then straight f keys for f7-f12. This mixed mode seems to be broken. Either I can send media control functions from all keys or f keys from all keys.

**Comment by mesqueeb** [comment]
Just here to confirm that a mix of F keys and media controls is no longer possible:
<img width="563" alt="image" src="https://github.com/user-attachments/assets/607efd64-4a0c-40f8-9ad3-1569176b9dff">

The **work around** now seems to apply F keys to all keys via macOS settings, then use the "Simple Modifications" to remap F keys back to media controls 😅

**Comment by jakebathman** [comment]
Thanks @mesqueeb, this workaround does indeed work for my use case, which I haven't seen explicitly mentioned here but will include for anyone who's doing the same thing.

I have an Apple Magic Keyboard (wireless, with num pad). I want the F* keys to be different between the built-in keyboard and my wireless extended keyboard (e.g., `F12` on extended can open dev tools in the browser, and `F12` on the built-in will always increase volume).

So to get this working, here's what's set:

|Setting|Value|
|:-----|:-----|
|System Settings: "Use F1... as standard function keys"|`On`|
|Karbiner: Function Keys|All reset to defaults (to avoid future issues if this feature is modified in future Karabiner versions)|
|Karabiner: Simple Modifications > Apple Internal Keyboard|`f12` → `volume_increment`|
|Karabiner: Simple Modifications > Wireless Keyboard|`f12` → `f12`|

**Comment by wosc** [comment]
Thank you very much for the quick response and new release, tekezo! I can confirm, using system settings makes the function keys work as themselves again.

There is one unfortunate interaction remaining, on a machine with touchbar, when you press Fn to switch that to function keys mode, those then perform "mute" instead of f10 (and so on). I don't mind this much, I hardly ever use the internal keyboard anyway, and if I do, I can switch off "use function keys" in system settings to make this case work.

**Comment by Jendker** [comment]
Is there a way to downgrade the driver to version from 15.0.0?

**Comment by tiojoca** [comment]
> Thanks @mesqueeb, this workaround does indeed work for my use case, which I haven't seen explicitly mentioned here but will include for anyone who's doing the same thing.
> 
> I have an Apple Magic Keyboard (wireless, with num pad). I want the F* keys to be different between the built-in keyboard and my wireless extended keyboard (e.g., `F12` on extended can open dev tools in the browser, and `F12` on the built-in will always increase volume).
> 
> So to get this working, here's what's set:
> 
> Setting	Value
> System Settings: "Use F1... as standard function keys"	`On`
> Karbiner: Function Keys	All reset to defaults (to avoid future issues if this feature is modified in future Karabiner versions)
> Karabiner: Simple Modifications > Apple Internal Keyboard	`f12` → `volume_increment`
> Karabiner: Simple Modifications > Wireless Keyboard	`f12` → `f12`

This works for me too, thanks @mesqueeb and @tekezo! This means Karabiner can use the same solution in the Functions Keys as is implemented for Simple Modifications (or maybe the Function Keys settings page should be removed since the same can be achieved with Simple Modifications) as long as the user is aware that they'll have to set  "Use F1... as standard function keys" system setting to `On`.

**Comment by tekezo** [comment]
Thank you for the detailed information!
I've fixed the f1...f12 key behavior in the latest beta version. Please try v15.2.1.

https://github.com/pqrs-org/Karabiner-Elements/releases/tag/beta

**Comment by iay** [comment]
@tekezo I have downloaded 15.2.1 but it doesn't look like it has changed anything in my situation. This is probably because I have misunderstood how to configure for my use case.

Here's what I am trying to do:

- Internal keyboard
  - F1 means brightness down
  - FN+F1 means F1
- External keyboard
  - F1 means F1
  - FN+F1 means brightness down

I've tried various settings of "use F... as standard function keys" and various settings for the F keys in Karabiner in both "simple modifications" and "function keys" but I haven't found a combination that gets me all of this. Closest I've got is one keyboard doing what I want (which is easy to do by selecting "use F... as standard function keys" appropriately) but then the other keyboard always gives whatever is set in Karabiner without taking Fn into account (same result with and without that key).

As I say, this is probably because I don't know how this is supposed to work. Can you suggest how I should configure things?

**Comment by igorlmatos** [comment]
First of all, I’d like to thank all the developers of this application. I really like it, and it makes a big difference in my daily routine. I solved my use case in the following way:

- Enabled the button so that the keys are used in their standard functions.
- Created a complex function for each function key. The idea is that most keys work with their media function, and when I press the fn key, they perform their standard function.
- For some keys, like F2 and F4, I wanted them to always function in their default mode when using Excel.

`{
    "description": "F2",
    "manipulators": [
        {
            "conditions": [
                {
                    "bundle_identifiers": [
                        "com.microsoft.Excel"
                    ],
                    "type": "frontmost_application_unless"
                }
            ],
            "from": {
                "key_code": "f2",
                "modifiers": { "optional": ["caps_lock"] }
            },
            "to": [{ "key_code": "display_brightness_increment" }],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "f2",
                "modifiers": {
                    "mandatory": ["fn"],
                    "optional": ["caps_lock"]
                }
            },
            "to": [{ "key_code": "f2" }],
            "type": "basic"
        }
    ]
}`

@iay, for your case, I believe you’ll need to use another condition, as explained in this link: https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/device/

**Comment by DanCates** [comment]
> The **work around** now seems to apply F keys to all keys via macOS settings, then use the "Simple Modifications" to remap F keys back to media controls 😅

@mesqueeb This works for me as well! Thanks.

**Comment by DanCates** [comment]
> > The **work around** now seems to apply F keys to all keys via macOS settings, then use the "Simple Modifications" to remap F keys back to media controls 😅
> 
> @mesqueeb This works for me as well! Thanks.

Actually, I take it back. This workaround only works if you're okay with having mappings permanently set and not variable based on pushing the function key. When I'm not using my external keyboard, I want to be able to use the internal keyboard and have the media controls when I push the function keys normally but then toggle the function keys when I hold the function key down. It doesn't seem to work that way any more. We seem to only get the single option for how things are remapped in Karabiner.

@mesqueeb @tekezo Is there a way to configure Karabiner such that holding function key toggles the mappings of the function keys? Like it normally would in macOS? I seem to be having the same issue as @iay described above. Unfortunately the new build 15.2.1 didn't seem to change anything.

**Comment by jefferickson** [comment]
Unfortunately I believe this is still broken on a basic level for the reason that the below configuration does not work. Pressing `F12` results in an `F12` event being sent and not a `volume_increment` event. While there may be a workaround, I think the basic functionality of the "Function Keys" tab isn't working.

![image](https://github.com/user-attachments/assets/cebbb08f-8b62-4a18-834b-dc0cd0da28cd)

```
[
  {
    "type": "down",
    "name": {"key_code":"f12"},
    "usagePage": "7 (0x0007)",
    "usage": "69 (0x0045)",
    "misc": ""
  },
  {
    "type": "up",
    "name": {"key_code":"f12"},
    "usagePage": "7 (0x0007)",
    "usage": "69 (0x0045)",
    "misc": ""
  }
]
```

I'm on Mac OS 15.0.1 on a Macbook Pro M3.

Thank you for the hard work!

**Comment by kuzlich** [comment]
![Screenshot 2024-10-09 at 10 22 07](https://github.com/user-attachments/assets/25d54046-fdf7-4c58-a930-721b5537983a)
Karabiner is still broken, and another problem has appeared. Even normal function keys stopped working. And it depends on the keyboard. On Mac, I see {“key_code”: “f1”}, on keychron {“consumer_key_code”: “display_brightness_decrement”}, and both keyboards have the f1 setting on the same button. There is a Win/mac switch on the keychron, this switch stopped working correctly. Duct taped it by putting the switch in Win mode and reconfiguring everything in Karabiner, and it works so far.

**Comment by AndiDog** [comment]
My use case works again with the beta 15.2.1: internal MacBook keyboard uses media keys, external keyboard maps F1-F12 to the function keys.

**Comment by torarnv** [comment]
@tekezo This setting is really nice, would it be possible to expose it as a "variable"?

<img width="362" alt="image" src="https://github.com/user-attachments/assets/2ae38e45-3f24-4e71-a1a7-d5312965d5b9">

So that a complex modification can choose to toggle it on and off based on the frontmost app? I normally want it off, because I want media keys, but it's nice to be able to override it with `fn`. But in some apps I want to switch the default, where pressing the keys without modifiers will give f1,f2,etc, but with fn gives the media keys.

**Comment by tekezo** [comment]
@jefferickson Thank you for feedback!
I updated the key names in Function Keys settings when "Use all F1, F2, etc. keys as standard function keys" is enabled in v15.2.2.

If you want to use f12 as volume control even if you don't hold the fn key, Please use Simple Modifications.

<img width="1100" alt="Screenshot 2024-10-23 at 8 55 31" src="https://github.com/user-attachments/assets/65b733f9-779e-400d-9bae-3e0c48ef8bdf">

**Comment by torarnv** [comment]
@tekezo Here is the use-case I'm trying to handle:

- By default
  - Function keys are used as media keys  
     - The functionality of each key specified in the "Function keys" UI in Karabiner Elements
  - Pressing fn+key gives F1/F2/etc
- In a select list of apps (Nvidia Geforce Now e.g.) 
   - Function keys are used as F1/F2/etc
   - Pressing fn+key gives media keys
      - The functionality of each key specified in the "Function keys" UI in Karabiner Elements

How would I solve this? As far as I understand this today requires a quite elaborate complex modification that duplicates the key->media key mapping already found in the  "Function keys" UI in Karabiner Elements?

**Comment by tekezo** [comment]
@torarnv 
The following complex modification rules swap F12 in Google Chrome.
In the same way, you can swap F1-F12 keys for specific applications only.

It’s important to change a key to fn+F12 if you want to send a regular F12 key.

```json
{
    "description": "f-keys example",
    "manipulators": [
        {
            "conditions": [
                {
                    "bundle_identifiers": [
                        "^com\\.google\\.Chrome$"
                    ],
                    "type": "frontmost_application_if"
                }
            ],
            "from": {
                "key_code": "f12",
                "modifiers": { "optional": ["caps_lock", "command", "control", "option", "shift"] }
            },
            "to": [
                {
                    "key_code": "f12",
                    "modifiers": ["fn"]
                }
            ],
            "type": "basic"
        },
        {
            "conditions": [
                {
                    "bundle_identifiers": [
                        "^com\\.google\\.Chrome$"
                    ],
                    "type": "frontmost_application_if"
                }
            ],
            "from": {
                "key_code": "f12",
                "modifiers": {
                    "mandatory": ["fn"],
                    "optional": ["any"]
                }
            },
            "to": [{ "consumer_key_code": "volume_increment" }],
            "type": "basic"
        }
    ]
}
```

**Comment by ansgarkroger** [comment]
In my case I wanted the builtin keyboard to trigger media keys but the external ones to work as function keys. I was able to do so using the following rule.
```
{
    "title": "Send Fn + Function key instead of Function key unless builtin",
    "rules": [
        {
            "description": "Rule: Fn + Fx instead of Fx unless builtin",
            "manipulators": [
                {
                    "conditions": [
                        {
                            "identifiers": [{ "is_built_in_keyboard": true }],
                            "type": "device_unless"
                        }
                    ],
                    "from": { "key_code": "f1" },
                    "to": [
                        {
                            "key_code": "f1",
                            "modifiers": ["fn"]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "identifiers": [{ "is_built_in_keyboard": true }],
                            "type": "device_unless"
                        }
                    ],
                    "from": { "key_code": "f2" },
                    "to": [
                        {
                            "key_code": "f2",
                            "modifiers": ["fn"]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "identifiers": [{ "is_built_in_keyboard": true }],
                            "type": "device_unless"
                        }
                    ],
                    "from": { "key_code": "f3" },
                    "to": [
                        {
                            "key_code": "f3",
                            "modifiers": ["fn"]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "identifiers": [{ "is_built_in_keyboard": true }],
                            "type": "device_unless"
                        }
                    ],
                    "from": { "key_code": "f4" },
                    "to": [
                        {
                            "key_code": "f4",
                            "modifiers": ["fn"]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "identifiers": [{ "is_built_in_keyboard": true }],
                            "type": "device_unless"
                        }
                    ],
                    "from": { "key_code": "f5" },
                    "to": [
                        {
                            "key_code": "f5",
                            "modifiers": ["fn"]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "identifiers": [{ "is_built_in_keyboard": true }],
                            "type": "device_unless"
                        }
                    ],
                    "from": { "key_code": "f6" },
                    "to": [
                        {
                            "key_code": "f6",
                            "modifiers": ["fn"]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "identifiers": [{ "is_built_in_keyboard": true }],
                            "type": "device_unless"
                        }
                    ],
                    "from": { "key_code": "f7" },
                    "to": [
                        {
                            "key_code": "f7",
                            "modifiers": ["fn"]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "identifiers": [{ "is_built_in_keyboard": true }],
                            "type": "device_unless"
                        }
                    ],
                    "from": { "key_code": "f8" },
                    "to": [
                        {
                            "key_code": "f8",
                            "modifiers": ["fn"]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "identifiers": [{ "is_built_in_keyboard": true }],
                            "type": "device_unless"
                        }
                    ],
                    "from": { "key_code": "f9" },
                    "to": [
                        {
                            "key_code": "f9",
                            "modifiers": ["fn"]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "identifiers": [{ "is_built_in_keyboard": true }],
                            "type": "device_unless"
                        }
                    ],
                    "from": { "key_code": "f10" },
                    "to": [
                        {
                            "key_code": "f10",
                            "modifiers": ["fn"]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "identifiers": [{ "is_built_in_keyboard": true }],
                            "type": "device_unless"
                        }
                    ],
                    "from": { "key_code": "f11" },
                    "to": [
                        {
                            "key_code": "f11",
                            "modifiers": ["fn"]
                        }
                    ],
                    "type": "basic"
                },
                {
                    "conditions": [
                        {
                            "identifiers": [{ "is_built_in_keyboard": true }],
                            "type": "device_unless"
                        }
                    ],
                    "from": { "key_code": "f12" },
                    "to": [
                        {
                            "key_code": "f12",
                            "modifiers": ["fn"]
                        }
                    ],
                    "type": "basic"
                }
            ]
        }
    ]
}
```

**Comment by torarnv** [comment]
Thank you @tekezo! However in example the media key functionality (`volume_increment`) is duplicating the mapping that has already been set in the Karbiner UI: 

![image](https://github.com/user-attachments/assets/07c5183c-13ff-439e-aaf9-e015f829a50f)

If I change the UI, the complex script will be out of sync. And if I share the complex modification rule to someone who has different mappings for Fn keys in the UI, the complex script will be "wrong" for them. Is there a way to do this without having the complex rule contain the mapping that already exists in the UI?

**Comment by tekezo** [comment]
@torarnv I added `system.use_fkeys_as_standard_function_keys` variable in Karabiner-Elements v15.2.3.
Will this solve the issue?
https://karabiner-elements.pqrs.org/docs/help/how-to/function-keys/#more-user-friendly-configuration

**Comment by torarnv** [comment]
Thanks @tekezo! Can confirm that following https://karabiner-elements.pqrs.org/docs/help/how-to/function-keys/#swap-f12-and-volume_increment-in-google-chrome works exactly as described in https://github.com/pqrs-org/Karabiner-Elements/issues/3954#issuecomment-2431426630, without needing to duplicate the mapping from f12->volume in the complex modification as well <3 

I don't need to read (or set) `system.use_fkeys_as_standard_function_keys` for this to work for me, but for a complex modification shared with others it will be useful, to be able to condition certain mappings on the current Fn key mode. Awesome!

**Comment by mesqueeb** [comment]
Anyone here tested the latest v15.3.0 Update?

**Comment by sst93** [comment]
I tested the latest v15.3.0 on MacOS 15.1 and it's working like it used to before MacOS 15. I turned off the use of function keys as standard function keys and mapped the function keys on my plugged in keyboard to the function keys (f1 -> f1, f2 -> f2, ...). So my use case (using media functions on internal mac keyboard on function keys and using the function keys on plugged in keyboards) works. Thanks :)

**Comment by leetdavid** [comment]
v15.3.0 has not fixed it for me. 

Here's my setup:
I use my mac keyboard like a 60% keyboard on most mechs.

I like to use the regular function keys as media keys as default (e.g. F1 -> display_brightness_decrement),
but fn + 1, 2, 3 is F1, F2, F3... and so on.

My setup was working fine for me until the new update, and v15.3.0 has not fixed the issue for me.
When I press fn + 1, I expect F1 to be pressed, but display_brightness_decrement is pressed instead.

**Comment by joexcm** [comment]
My old setup is also still not working.
Do we need to rewrite them in order for them to work now or are we waiting for a fix? Thanks everyone

**Comment by tekezo** [comment]
To send raw F1–F12 keys, you'll need to modify the rules to send Fn+F1 through Fn+F12.
https://karabiner-elements.pqrs.org/docs/help/how-to/function-keys/

**Comment by Json1040** [comment]
> To send raw F1–F12 keys, you'll need to modify the rules to send Fn+F1 through Fn+F12. https://karabiner-elements.pqrs.org/docs/help/how-to/function-keys/

I don't even know how to write a script, so I'm stuck with my external keyboard _and_ my internal keyboards Fn keys being forcibly turned into Media Controls, unless I press Fn + F# for it to actually work. Is it possible to get a bit of help with it? The scripts on the wiki are made for an application or a specific use case. I just want a blanket, "all Fn keys pressed will work as they would if you pressed Fn + Fx", and i can't even make it. Also I've searched the Subreddit, along with essentially all other sources for something like this, _and there's **nothing.**_ This is also all on 15.3.0 as well.

**Comment by Romasato** [comment]
This is still an issue with 15.4.0 - Karabiner is not picking up MacOS system setting for "Use all F1, F2, etc. keys as standard function keys" and always shows as "Off", even though in System Settings it is enabled. Is this a known issue?

<img width="1212" alt="Image" src="https://github.com/user-attachments/assets/235a6368-6517-4a99-8227-d72879cae00a" />

Any advice how to fix this will be much appreciated. 

Thanks

**Comment by tekezo** [comment]
@Romasato Thanks for the feedback. I confirmed that the same issue occurs in cases where multiple users are using a Mac. I'll work on a fix.

**Comment by tekezo** [comment]
@Romasato This issue has been fixed in v15.4.2.
Please check if it's working as expected in your environment as well.
https://github.com/pqrs-org/Karabiner-Elements/releases/tag/beta

**Comment by Romasato** [comment]
Hi @tekezo,

Thank you for the update. 

Just trying the new beta v15.4.2, I can see the "Standard Function Keys" indicator reflects the System Settings state now. 

It also seems to have partially fixed the problem of Fx keys not working, but not entirely - the FN+F8 for audio playback START/RESUME is not working. 

Let me demonstrate:

<img width="1212" height="844" alt="Image" src="https://github.com/user-attachments/assets/3cdb7eeb-397b-4fbb-a77c-2a47259d5faf" />

I override FN (GLOBE) key to act as LEFT CTRL and then configure RIGHT OPTION to act as (FN) GLOBE key instead.

<img width="1212" height="844" alt="Image" src="https://github.com/user-attachments/assets/cdbc6ddd-2550-414f-9906-9df1402d488b" />

At this point, RIGHT OPTION + F10/F11/F12 works to control volume as expected.

But weirdly RIGHT OPTION + F7/F8/F9 does not control playback (testing with Spotify), though Karabiner Events Viewer reports expected `consumer_key_code` of `play_or_pause`:

<img width="1728" height="1042" alt="Image" src="https://github.com/user-attachments/assets/4649a083-32a2-4258-8238-fd37d2c4a0ec" />

If I quit Karabiner, using the native FN (GLOBE) + F8 does work to start/stop playback of Spotify. 

Any ideas? 

Thank you

**Comment by tekezo** [comment]
I tested it on my end, and after remapping the right option key to fn, pressing right option + f8 triggers play/pause as expected.
For example, does the issue also occur in apps like Music.app?

If the issue only occurs with Spotify, it's possible that Spotify is handling the keys in a special way on its end.
Will it start working if you add the following Complex Modification?
This configuration removes the fn modifier from the play_or_pause action.

How to use:
https://karabiner-elements.pqrs.org/docs/manual/configuration/add-your-own-complex-modifications/

```json
{
    "description": "Change fn+f8 to play_or_pause",
    "manipulators": [
        {
            "from": {
                "key_code": "f8",
                "modifiers": {
                    "mandatory": ["fn"],
                    "optional": ["any"]
                }
            },
            "to": [{ "consumer_key_code": "play_or_pause" }],
            "type": "basic"
        }
    ]
}
```

**Comment by Romasato** [comment]
Hi @tekezo,

I thought so too initially that maybe Spotify is handling keys in some non-standard way, but YouTube playback (in Opera browser) was not reacting either - unless I quit Karabiner and pressed FN (GLOBE) + F8.

With your complex modification it does work though, both Spotify and YouTube 👍 
 
Inspecting EventViewer, the events are triggered the same (but maybe in a slightly different order) - either with or without the mod, so it's a bit confusing.

<img width="1207" height="708" alt="Image" src="https://github.com/user-attachments/assets/0ab020f8-66a0-43dd-b2d4-1193ba35d330" />

Hope that helps to identify the cause.

Thanks again

**Comment by tekezo** [comment]
@Romasato 
Thank you for your confirmation!

It's likely that apps like Spotify and Opera can't handle the play_or_pause event properly when it's sent with the fn modifier active.
I'm glad to hear that using a Complex Modification solved the issue.

That said, there's a known trade-off with this setting: if macOS is configured to assign a function to tapping the fn key, that function may be unintentionally triggered when pressing right option + f8.
Because of this trade-off, we've intentionally kept the current behavior as-is.

We don't plan to change this as the default behavior, so please continue to use Complex Modifications to address this type of case going forward.

**Comment by Romasato** [comment]
Hi @tekezo, 

It's good you mentioned MacOS configuration side of things, I went to `Keyboard -> Keyboard Shortcuts -> Modifier Keys` and noticed that **Karabiner DriverKit VirtualHIDKeyboard** was configured to map FN GLOBE to CTRL. 

<img width="716" height="806" alt="Image" src="https://github.com/user-attachments/assets/83c1480a-08d8-49d8-b64f-13034907a58d" />

I've changed it back to the default FN GLOBE -> FN GLOBE and now the remapped in Karabiner RIGHT OPTION as FN + F8 works as expected to PLAY/PAUSE the multimedia :)

So I guess there are two places where mappings can be changed, both via MacOS System settings and on Karabiner - and they get layered together somehow.

Anyway, looks like problem is solved.

Thanks for your help :)

**Comment by tekezo** [comment]
Ah, I see. That behavior makes sense. Glad to hear the issue is resolved!

**Comment by keichinger** [comment]
Weirdly enough, I have the *very same* remappings as @Romasato since I got the new Apple Magic Keyboard with TouchID. It was confusing the hell out of me that both my ><< and ^ keys (I've got the DE-ISO version) were flipped as soon as the keyboard was connected (which also applies to the built-in keyboard of my MacBook Pro M1), which was even the reason why I had to use Karabiner 😅 

What was even **more confusing** to me was that I've also encountered the very same media key issues as long as Karabiner was opened after I upgraded my macOS a while ago, on both my TouchID keyboard and my old wired keyboard. Closing Karabiner has helped, but it wasn't an option for me.

So the complex rule, as suggested in https://github.com/pqrs-org/Karabiner-Elements/issues/3954#issuecomment-3085842033 by @tekezo is indeed working! Thaaaaaank you so much for this <3

High-five to @tekezo for being an amazing person, and high-five to @Romasato for probably having the very same muscle memory and key mapping issues as I have :D

**Comment by marek-elisity** [comment]
<img width="1093" height="645" alt="Image" src="https://github.com/user-attachments/assets/b4e08cef-f730-4dbe-991a-3faedf109a1f" />

<img width="1095" height="680" alt="Image" src="https://github.com/user-attachments/assets/4ab9719f-4d1d-4938-990e-ba924ceff66b" />

This is my workaround. Works perfectly. No need to press any fn nor ctrl.
External keyboard: F1-F12
Internal: those I use I've modified e.g., F1 -> brightness decrement, etc.
