### ISSUE TITLE
Can't get my complex modification to work as expected.

### ISSUE THREAD

**Issue by jacques-kigo** [pqrs-org/Karabiner-Elements#3975]
What I'm trying to do:

1. Map `CapsLock` to `Option+LShift+LeftArrow,Backspace` to delete the previous word.
2. Map `LShift+CapsLock` to toggle normal caps lock functionality On and Off.

```json
{
  "description": "CapsLock to delete previous word, LShift+CapsLock to toggle CapsLock",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "key_code": "left_shift",
        "modifiers": {
          "mandatory": ["caps_lock"]
        }
      },
      "to": [
        {
          "key_code": "caps_lock"
        }
      ]
    },
    {
      "type": "basic",
      "from": {
        "key_code": "caps_lock",
        "modifiers": {
          "optional": ["any"]
        }
      },
      "to": [
        {
          "key_code": "left_arrow",
          "modifiers": ["left_option", "left_shift"]
        },
        {
          "key_code": "delete_or_backspace"
        }
      ]
    }
  ]
}
```

I can get the first part working fine to delete the previous word, but toggle caps lock on and off won't work correctly. It will toggle on, but won't toggle off.

**Comment by inrsta** [comment]
I'll add my issue here because I believe they are related. Under the current set up When pressed alone, Caps Lock used to toggle on and off. Since some time (I am unfortuntately not sure exactly when) this is not the case anymore. 
```json
        {
            "description": "Hyper Key (⌃⌥⇧⌘)",
            "manipulators": [
              {
                "description": "Caps Lock -> Hyper Key",
                "from": {
                  "key_code": "caps_lock"
                },
                "to": [
                  {
                    "key_code": "left_shift",
                    "modifiers": [
                      "left_command",
                      "left_control",
                      "left_option"
                    ]
                  }
                ],
                "to_if_alone": [
                  {
                    "key_code": "caps_lock"
                  }
                ],
                "type": "basic"
              }
            ]
          }
```

**Comment by schoblaska** [comment]
Spooky! My Caps Lock complex modification just stopped working as well.

```json
{
  "description": "CAPS to CTRL+OPT if pressed with other keys, ESC if pressed alone.",
  "manipulators": [
    {
      "from": {
        "key_code": "caps_lock",
        "modifiers": {
          "optional": ["any"]
        }
      },
      "to": [
        {
          "key_code": "left_control",
          "modifiers": ["left_option"]
        }
      ],
      "to_if_alone": [
        {
          "key_code": "escape"
        }
      ],
      "type": "basic"
    }
  ]
}
```

**Comment by schoblaska** [comment]
Even spookier: after a restart, today it started working again. I had tried restarting last night when I first noticed the issue and nothing happened. This morning it worked 🤷

**Comment by jacques-kigo** [comment]
Weird. This doesn't appear to be the most stable or intuitive application. I was able to get this working quite well with AutoHotKey on windows and I'm trying to recreate that behavior on my Mac.

**Comment by inrsta** [comment]
I also wanted to report the following:

```
❯ launchctl kickstart -k gui/`id -u`/org.pqrs.karabiner.karabiner_console_user_server
Could not find service "org.pqrs.karabiner.karabiner_console_user_server" in domain for user gui: 501
```

I am on MacOS 15.0.1 (24A348), Karabiner-Elements 15.2.0

**Comment by JupitorCentral** [comment]
Me either. complex rules which worked well before started not working after updating Karabiner to 15.2.0.

**Comment by JupitorCentral** [comment]
> Me either. complex rules which worked well before started not working after updating Karabiner to 15.2.0. just in case, I upgraded my mac os to Sequoia to 15.1.

My complex rule was when press f1..f12 key at outer keyboard, then work like f1...f12 key not media key. 
and after upgraded Karabiner to 15.2.0, it stopped.

after update this app to beta, 15.2.2 it worked again. 
(https://github.com/pqrs-org/Karabiner-Elements/releases/tag/beta)
so my problem is solved.

**Comment by sikaco** [comment]
> > Me either. complex rules which worked well before started not working after updating Karabiner to 15.2.0. just in case, I upgraded my mac os to Sequoia to 15.1.
> 
> My complex rule was when press f1..f12 key at outer keyboard, then work like f1...f12 key not media key. and after upgraded Karabiner to 15.2.0, it stopped.
> 
> after update this app to beta, 15.2.2 it worked again. (https://github.com/pqrs-org/Karabiner-Elements/releases/tag/beta) so my problem is solved.

Good news, I will try it later.
Currently, my solutions is degrade this app to 14.13.0, it resolve my problem.

**Comment by YusufGandhi** [comment]
I was frustrated as well with this and found out that there's an [important breaking change log hidden in version 15.1.0](https://karabiner-elements.pqrs.org/docs/help/troubleshooting/breaking-changes/#karabiner-elements-1510)

<img width="835" alt="image" src="https://github.com/user-attachments/assets/8b253c07-fcf6-410e-bc4f-6a09c3a96a56">

So, if you want to use Caps Lock in Complex Modification, you need to add `hold_down_milliseconds` ([link](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to/hold-down-milliseconds/)) like the following:

<img width="786" alt="image" src="https://github.com/user-attachments/assets/4cbecb6c-06f4-47b2-8d17-ae65cc80dc65">

For me, just adding the following line for my caps lock Complex Modification works like a charm:
```
"hold_down_milliseconds": 100
```

**Comment by jamesalmeida** [comment]
This doesn't seem to work for me. Added "hold_down_milliseconds": 200 but still won't work on caps_lock...
