### ISSUE TITLE
Tahoe upgrade issue: karabiner_grabber has disappeared from the Input Monitoring Settings.

### ISSUE THREAD

**Issue by yuzijie** [pqrs-org/Karabiner-Elements#4313]
After upgraded to Tahoe 26.1, karabiner_grabber had disappeared
Karabiner is working fine now, but this will affect new installation, because the permission cannot be granted.

<img width="835" height="1034" alt="Image" src="https://github.com/user-attachments/assets/26eb567c-735f-4f16-b49e-4159e159f351" />

**Comment by tekezo** [comment]
Thank you! I've confirmed the issue.

related: https://github.com/pqrs-org/Karabiner-Elements/issues/4309

**Comment by Brodzko** [comment]
Just spent a while wrestling with this after a fresh MacOS install. No reinstalls or device restarts helped. Eventually I had to go to `Settings -> Privacy & Security -> Input Monitoring` and find and add `karabiner_grabber`. it lives in `/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_grabber` (the _global_ `Library`, not the user's one). I also had to manually enable the Driver Extension for the DeviceManager in Login Items.

`karabiner_grabber` is still not showing in the Input Monitoring section but the issue is now resolved and so far persisted even through system restarts.

Nitpick: It was pretty annoying trying to read the log console while the app kept asking for permissions I could not grant every 2-3 seconds (:

Edit: Fixed path

**Comment by tekezo** [comment]
I've addressed this issue at the latest beta (v15.6.91).

[How to upgrade to the latest beta version](https://karabiner-elements.pqrs.org/docs/manual/operation/check-for-updates/#using-the-latest-beta-version)

**Comment by serhanguney** [comment]
I'm stuck at the pop up that appears on launch and says to allow the driver extension. **The driver extension is not visible**. I tried deactivating the driver and restarting mac as the pop up suggests but the issue still isnt resolved. The pop up is still there. I tried uninstalling and installed again but still the same issue :/

<img width="1086" height="721" alt="Image" src="https://github.com/user-attachments/assets/973d5ee6-3e34-43d5-8eab-5c840bedce5a" />

<img width="1086" height="728" alt="Image" src="https://github.com/user-attachments/assets/5c9061bb-30df-477b-9a58-a93fd651623e" />

<img width="709" height="774" alt="Image" src="https://github.com/user-attachments/assets/33f6d7e9-c720-47de-97ed-631b819ed5f9" />

<img width="701" height="736" alt="Image" src="https://github.com/user-attachments/assets/354426e1-5c05-41ca-9265-fbf1408b99ba" />
